samplemetadatamap = { 
 "SAMPLE_METADATA" : 
 {
  "SAMPLE_ID"  : {}, 
  "STUDY_ID"  : {},
  "SAMPLE_NAME" : {},
  "PUBLIC"  : {},
  "ASSIGNED_FROM_GEO"  : {},
  "ALTITUDE" : {},
  "CHEM_ADMINISTRATION"  : {},
  "COLLECTION_DATE" : {},
  "COUNTRY" : {},
  "DEPTH"  : {},
  "ELEVATION" : {},
  "ENV_BIOME" : {},
  "ENV_FEATURE" : {},
  "ENV_MATTER" : {},
  "ORGANISM_COUNT" : {},
  "OXY_STAT_SAMP"  : {},
  "PERTURBATION"  : {},
  "PH" : {},
  "LATITUDE" : {},
  "LONGITUDE" : {},
  "SAMP_COLLECT_DEVICE" : {},
  "SAMP_MAT_PROCESS" : {},
  "SAMP_SALINITY" : {},
  "SAMP_SIZE" : {},
  "SAMP_STORE_DUR" : {},
  "SAMP_STORE_LOC" : {},
  "SAMP_STORE_TEMP" : {},
  "TEMP" : {},
  "TITLE" : {},
  "TAXON_ID"  : {},
  "COMMON_NAME" : {},
  "ANONYMIZED_NAME" : {},
  "DESCRIPTION"  : {},
  "BIOLOGICAL_SPECIMEN" : {},
  "EXTRACTED_DNA_AVAIL_NOW"  : {},
  "PHYSICAL_SAMP_AVAIL_NOW"  : {}
      }, 
  
 "COMMON_FIELDS" : 
 {
  "SAMPLE_ID"  : {},
  "ALKALINITY" : {},
  "ALKYL_DIETHERS" : {},
  "AMINOPEPT_ACT" : {},
  "AMMONIUM" : {},
  "BACTERIA_CARB_PROD" : {},
  "BIOMASS" : {},
  "BISHOMOHOPANOL" : {},
  "BROMIDE" : {},
  "CALCIUM" : {},
  "CARB_NITRO_RATIO" : {},
  "CHLORIDE" : {},
  "CHLOROPHYLL" : {},
  "CURRENT" : {},
  "DENSITY" : {},
  "DIETHER_LIPIDS" : {},
  "DISS_CARB_DIOXIDE" : {},
  "DISS_HYDROGEN" : {},
  "DISS_ORG_CARBON" : {},
  "DISS_OXYGEN" : {},
  "GLUCOSIDASE_ACT" : {},
  "MAGNESIUM" : {},
  "MEAN_FRICT_VEL" : {},
  "MEAN_PEAK_FRICT_VEL" : {},
  "METHANE" : {},
  "MISC_PARAM"  : {},
  "N_ALKANES" : {},
  "NITRATE" : {},
  "NITRITE" : {},
  "NITRO" : {},
  "ORG_CARB" : {},
  "ORG_MATTER" : {},
  "ORG_NITRO" : {},
  "ORGANISM_COUNT" : {},
  "OXYGEN" : {},
  "PART_ORG_CARB" : {},
  "PETROLEUM_HYDROCARB" : {},
  "PH" : {},
  "PHAEOPIGMENTS" : {},
  "PHOSPHATE" : {},
  "PHOSPLIPID_FATT_ACID" : {},
  "POTASSIUM" : {},
  "PRESS" : {},
  "REDOX_POTENTIAL" : {},
  "SALINITY" : {},
  "SILICATE" : {},
  "SULFATE" : {},
  "SULFIDE" : {},
  "TOT_CARB" : {},
  "TOT_NITRO" : {},
  "TOT_ORG_CARB" : {},
  "TURBIDITY" : {},
  "WATER_CONTENT"  : {}
      }, 

 "DIET_COMPONENETS" : 
 {
  "EXP_DIET_ID"  : {},
  "PERENT_CARBO" : {},
  "PERCENT_FAT" : {},
  "PERCENT_PROTEIN" : {},
  "PERCENT_STARCH"   : {}
    },  

 "HOST_ASSOCIATED_PLANT" : 
 {
  "AIR_TEMP_REGM" : {},
  "ANTIBIOTIC_REGM" : {},
  "CHEM_MUTAGEN" : {},
  "CLIMATE_ENVIRONMENT" : {},
  "FERTILIZER_REGM" : {},
  "FUNGICIDE_REGM" : {},
  "GASEOUS_ENVIRONMENT" : {},
  "GRAVITY" : {},
  "GROWTH_HORMONE_REGM" : {},
  "GROWTH_MED" : {},
  "HERBICIDE_REGM" : {},
  "HUMIDITY_REGM" : {},
  "INFRA_SPECIFIC_NAME" : {},
  "INFRA_SPECIFIC_RANK" : {},
  "LIFE_STAGE" : {},
  "MECHANICAL_DAMAGE" : {},
  "MINERAL_NUTR_REGM" : {},
  "NON_MINERAL_NUTR_REGM" : {},
  "PESTICIDE_REGM" : {},
  "PH_REGM" : {},
  "PLANT_BODY_SITE" : {},
  "PLANT_PRODUCT" : {},
  "RADIATION_REGM" : {},
  "RAINFALL_REGM" : {},
  "SALT_REGM" : {},
  "SEASON_ENVIRONMENT" : {},
  "STANDING_WATER_REGM" : {},
  "TISS_CULT_GROWTH_MED" : {},
  "WATER_TEMP_REGM" : {},
  "WATERING_REGM" : {},
  "WET_MASS"   : {}
    },  

 "HOST_ASSOC_VERTIBRATE" : 
 {
  "BODY_HABITAT" : {},
  "BODY_SITE" : {},
  "BODY_PRODUCT" : {},
  "BLOOD_PRESS_DIAST" : {},
  "BLOOD_PRESS_SYST" : {},
  "HOST_BODY_TEMP" : {},
  "DIET"  : {},
  "FAMILY_RELATIONSHIP" : {},
  "MEDICATIONS" : {},
  "GRAVIDITY"  : {},
  "GRAVIDITY_DUE_DATE" : {},
  "HOST_GROWTH_COND" : {},
  "LAST_MEAL" : {},
  "SCIENTIFIC_NAME" : {},
# controlled vocab..skip for now
#  "SEX"  : {},
  "SUBSTRATE" : {},
  "TIME_SINCE_LAST_MEDICATION" : {},
  "DATE_OF_BIRTH" : {},
  "SAMPLE_ID"    : {}
    },  
               
 "HOST" :
 {
    "HOST_COMMON_NAME" : {},
    "HOST_TAXID" : {},
    "HOST_SUBJECT_ID" : {}
  },

 "HOST_SAMPLE" : 
 {
  "AGE" : {},
  "AGE_UNIT"  : {},
  "DISEASE_STAT"  : {},
  "DRY_MASS" : {},
  "GENOTYPE" : {},
  "HEIGHT_OR_LENGTH" : {},
  "INFRA_SPECIFIC_NAME" : {},
  "INFRA_SPECIFIC_RANK"  : {},
  "LIFE_STAGE" : {},
  "PHENOTYPE" : {},
  "TOTAL_MASS" : {},
  "HOST_COLOR"  : {},
  "HOST_SHAPE"    : {}
    },  

 "HUMAN_ASSOCIATED" : 
 {
  "BODY_MASS_INDEX" : {},
  "DRUG_USAGE" : {},
  "HIV_STAT"  : {},
  "IHMC_ETHNICITY" : {},
  "IHMC_OCCUPATION"  : {},
  "LAST_MEAL" : {},
  "DIET_LAST_SIX_MONTH" : {},
  "MEDIC_HIST_PERFORM"  : {},
  "PET_FARM_ANIMAL" : {},
  "PULSE" : {},
  "SMOKER"  : {},
  "TRAVEL_OUT_SIX_MONTH" : {},
  "TWIN_SIBLING"  : {},
  "WEIGHT_LOSS_3_MONTH" : {},
  "NOSE_THROAT_DISORD" : {},
  "PULMONARY_DISORD" : {},
  "STUDY_COMPLT_STAT"  : {},
  "AMNIOTIC_FLUID_COLOR"  : {},
  "GESTATION_STATE" : {},
  "FOETAL_HEALTH_STAT" : {},
  "MATERNAL_HEALTH_STAT" : {},
  "BLOOD_DISORD" : {},
  "GASTROINTEST_DISORD" : {},
  "LIVER_DISORD" : {},
  "SPECIAL_DIET" : {},
  "NOSE_MOUTH_TEETH_THROAT_DISORD" : {},
  "TIME_LAST_TOOTHBRUSH" : {},
  "DERMATOLOGY_DISORD" : {},
  "DOMINANT_HAND"  : {},
  "TIME_SINCE_LAST_WASH" : {},
  "KIDNEY_DISORD" : {},
  "URINE_COLLECT_METH"  : {},
  "UROGENIT_TRACT_DISOR" : {},
  "BIRTH_CONTROL"  : {},
  "DOUCHE" : {},
  "GYNECOLOGIC_DISORD" : {},
  "MENARCHE" : {},
  "HRT" : {},
  "HYSTERECTOMY"  : {},
  "MENOPAUSE" : {},
  "PREGNANCY" : {},
  "SEXUAL_ACT" : {},
  "UROGENIT_DISORD" : {},
  "SAMPLE_ID"    : {}
      }, 

 
 "SEDIMENT" : 
 {
  "SAMPLE_ID"  : {},
  "PARTICLE_CLASS" : {},
  "POROSITY" : {},
  "SEDIMENT_TYPE"   : {}
    },  

"AIR" : 
{
  "SAMPLE_ID"  : {},
  "BAROMETRIC_PRESS" : {},
  "CARB_DIOXIDE" : {},
  "CARB_MONOXIDE" : {},
  "HUMIDITY" : {},
  "POLLUTANTS" : {},
  "RESP_PART_MATTER" : {},
  "SOLAR_IRRADIANCE" : {},
  "VENTILATION_RATE" : {},
  "VENTILATION_TYPE" : {},
  "VOLATILE_ORG_COMP" : {},
# controlled vocab...skip for now
#  "WIND_DIRECTION"  : {},
  "WIND_SPEED"   : {}
    }, 
  



 "SOIL" : 
 {
  "SAMPLE_ID"  : {},
# a controlled vocabulary so don't know how to do it yet
#  "CUR_LAND_USE"  : {},
  "CUR_VEGETATION" : {},
  "CUR_VEGETATION_METH" : {},
  "PREVIOUS_LAND_USE" : {},
  "PREVIOUS_LAND_USE_METH" : {},
  "CROP_ROTATION" : {},
  "AGROCHEM_ADDITION" : {},
  "TILLAGE" : {},
  "FIRE" : {},
  "FLOODING" : {},
  "EXTREME_EVENT" : {},
  "OTHER"  : {},
  "HORIZON"  : {},
  "HORIZON_METH" : {},
  "SIEVING" : {},
  "WATER_CONTENT_SOIL" : {},
  "WATER_CONTENT_SOIL_METH" : {},
  "SAMP_WEIGHT_DNA_EXT" : {},
  "POOL_DNA_EXTRACTS"  : {},
  "STORE_COND" : {},
  "LINK_CLIMATE_INFO" : {},
  "ANNUAL_SEASON_TEMP" : {},
  "ANNUAL_SEASON_PRECPT" : {},
  "LINK_CLASS_INFO" : {},
  "FAO_CLASS" : {},
  "LOCAL_CLASS" : {},
  "LOCAL_CLASS_METH" : {},
  "SOIL_TYPE" : {},
  "SOIL_TYPE_METH" : {},
  "SLOPE_GRADIENT" : {},
  "SLOPE_ASPECT" : {},
  "PROFILE_POSITION" : {},
  "DRAINAGE_CLASS" : {},
  "TEXTURE" : {},
  "TEXTURE_METH" : {},
  "PH_METH" : {},
  "TOT_ORG_C_METH" : {},
  "TOT_N_METH" : {},
  "MICROBIAL_BIOMASS" : {},
  "MICROBIAL_BIOMASS_METH" : {},
  "LINK_ADDIT_ANALYS" : {},
  "EXTREME_SALINITY" : {},
  "SALINITY_METH" : {},
  "HEAVY_METALS" : {},
  "HEAVY_METALS_METH" : {},
  "AL_SAT" : {},
  "AL_SAT_METH" : {}
    },  

 "SRA_SUBMISSION" : 
 {
  "STUDY_ID"  : {},
  "ACCESSION" : {},
  "SUBMISSION_ID" : {},
  "SUBMISSION_COMMENT"  : {},
  "LAB_NAME" : {},
  "SUBMISSION_DATE"  : {},
  "CONTACT" : {},
  "FILE"    : {}
    },  

 "STUDY" :
  {
  "STUDY_ID"  : {},
  "SUBMIT_TO_INSDC"  : {},
  "INVESTIGATION_TYPE"  : {},
  "PROJECT_NAME" : {},
  "EXPERIMENTAL_FACTOR"  : {},
  "METADATA_COMPLETE"  : {},
  "STUDY_ALIAS" : {},
  "STUDY_TITLE" : {},
  "STUDY_TYPE"  : {},
  "STUDY_ABSTRACT"  : {},
  "STUDY_DESCRIPTION"  : {},
  "CENTER_NAME" : {},
  "CENTER_PROJECT_NAME" : {},
  "PROJECT_ID" : {},
  "PMID" : {},
  "MIENS_COMPLIANT" : {},
  "STUDY_PUBLIC"  : {},
  "PORTAL_TYPE" : {},
  "INT_SAMPLES_PROMISED"  : {},
  "PRINCIPAL_INVESTIGATOR" : {},
  "INT_SAMPLES_COLLECTED"  : {},
  "LAB_PERSON" : {},
  "LAB_PERSON_CONTACT" : {},
  "EMP_PERSON" : {},
  "FIRST_CONTACT" : {},
  "MOST_RECENT_CONTACT" : {},
  "SAMPLE_TYPE" : {},
  "HAS_PHYSICAL_SPECIMEN" : {},
  "HAS_EXTRACTED_DATA" : {},
  "TIMESERIES" : {},
  "SPATIAL_SERIES" : {},
  "PRINCIPAL_INVESTIGATOR_CONTACT"   : {}
    },  


"WASTEWATER_SLUDGE" : 
{
    "SAMPLE_ID"  : {},
  "BIOCHEM_OXYGEN_DEM" : {},
  "CHEM_OXYGEN_DEM" : {},
  "EFFICIENCY_PERCENT" : {},
  "EMULSIONS" : {},
  "GASEOUS_SUBSTANCES" : {},
  "INDUST_EFF_PERCENT" : {},
  "INORG_PARTICLES" : {},
  "ORG_PARTICLES" : {},
  "PRE_TREATMENT" : {},
  "PRIMARY_TREATMENT" : {},
  "REACTOR_TYPE" : {},
  "SECONDARY_TREATMENT" : {},
  "SEWAGE_TYPE" : {},
  "SLUDGE_RETENT_TIME" : {},
  "SOLUBLE_INORG_MAT" : {},
  "SOLUBLE_ORG_MAT" : {},
  "SUSPEND_SOLIDS" : {},
  "TERTIARY_TREATMENT" : {},
  "TOT_PHOSPHATE" : {},
  "WASTEWATER_TYPE"   : {}
    },  

 "WATER" : 
 {
  "SAMPLE_ID"  : {},
  "ATMOSPHERIC_DATA": {},
  "DISS_INORG_NITRO" : {},
  "DISS_INORG_PHOSP" : {},
  "LIGHT_INTENSITY" : {},
  "PHOTON_FLUX" : {},
  "PRIMARY_PROD" : {},
  "SOLUBLE_REACT_PHOSP" : {},
  "SUSPEND_PART_MATTER" : {},
  "TOT_DEPTH_WATER_COL" : {},
  "TOT_INORG_NITRO" : {},
  "TOT_PART_CARB" : {},
  "TOT_PHOSP"   : {}
    }
}

sequencemetadatamap = {          
 "SEQUENCE_PREP" : 
 {
    "SEQUENCE_PREP_ID"  : {},
    "SAMPLE_ID"  : {},
    "NUCL_ACID_EXT"  : {},
    "NUCL_ACID_AMP"  : {},
    "LIB_SIZE"  : {},
    "LIB_READS_SEQD"  : {},
    "LIB_VECTOR"  : {},
    "LIBR_SCREEN"  : {},
    "TARGET_GENE" : {},
    "TARGET_SUBFRAGMENT" : {},
    "PCR_PRIMERS"  : {},
    "MULTIPLEX_IDENT" : {},
    "PCR_COND"  : {},
    "SEQUENCING_METH" : {},
    "SEQ_QUALITY_CHECK"  : {},
    "CHIMERA_CHECK"  : {},
    "SOP"  : {},
    "URL"  : {},
    "EXPERIMENT_ALIAS" : {},
    "EXPERIMENT_CENTER" : {},
    "EXPERIMENT_TITLE" : {},
    "EXPERIMENT_ACCESSION" : {},
    "STUDY_ACCESSION" : {},
    "STUDY_REF" : {},
    "STUDY_CENTER" : {},
    "EXPERIMENT_DESIGN_DESCRIPTION"  : {},
    "LIBRARY_CONSTRUCTION_PROTOCOL"  : {},
    "SAMPLE_ACCESSION" : {},
    "SAMPLE_ALIAS" : {},
    "SAMPLE_CENTER" : {},
    "POOL_MEMBER_ACCESSION" : {},
    "POOL_MEMBER_NAME" : {},
    "POOL_PROPORTION" : {},
    "BARCODE_READ_GROUP_TAG" : {},
    "BARCODE" : {},
    "LINKER" : {},
    "KEY_SEQ" : {},
    "PRIMER_READ_GROUP_TAG" : {},
    "PRIMER" : {},
    "RUN_PREFIX" : {},
    "REGION" : {},
    "PLATFORM" : {},
    "RUN_ACCESSION" : {},
    "RUN_ALIAS" : {},
    "RUN_CENTER" : {},
    "RUN_DATE" : {},
    "INSTRUMENT_NAME" : {},
    "LIBRARY_STRATEGY" : {},
    "LIBRARY_SOURCE" : {},
    "LIBRARY_SELECTION" : {},
    "ROW_INT"    : {},
    "metagenome_name" : {},
    "seq_meth" : {},
    "seq_center" : {},
    "seq_url" : {},
    "seq_make" : {},
    "seq_model" : {},
    "seq_chem" : {},
    "seq_direction" : {},
    "domain" : {},
    "forward_barcodes" : {},
    "reverse_barcodes" : {},
    "forward_primers" : {},
    "reverse_primers" : {},
    "thermocycler" : {},
    "run_machine_type" : {},
    "cloning_kit" : {},
    "host_cells" : {},
    "amp_polymerase" : {},
    "cycle_count" : {},
    "cycle_annealing_duration" : {},
    "cycle_annealing_temp" : {},
    "cycle_annealing_method" : {},
    "cycle_denaturation_duration" : {},
    "cycle_denaturation_temp" : {},
    "cycle_extension_duration" : {},
    "cycle_extension_temp" : {},
    "denaturation_duration_initial" : {},
    "denaturation_temp_initial" : {},
    "extension_duration_final" : {},
    "extension_temp_final" : {},
    "forward_primer_final_conc" : {},
    "reverse_primer_final_conc" : {},
    "dATP_final_conc" : {},
    "dCTP_final_conc" : {},
    "dGTP_final_conc" : {},
    "dTTP_final_conc" : {},
    "gelatin_final_conc" : {},
    "BSA_final_conc" : {},
    "KCl_final_conc" : {},
    "MgCl2_final_conc" : {},
    "Tris_HCl_final_conc" : {},
    "library_institute" : {},
    "library_notes" : {},
    "local_NAP_ids" : {},
    "NAP_volume" : {},
    "pcr_clean_up_kits" : {},
    "pcr_clean_up_methods" : {},
    "pcr_notes" : {},
    "pcr_replicates" : {},
    "pcr_buffer_pH" : {},
    "pcr_volume" : {},
    "polymerase_units" : {},
    "tail_polymerase" : {},
    "tail_duration" : {},
    "tail_temp" : {},
    "other_additives" : {}
    }
}
